# Generated by Django 5.2.3 on 2025-06-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='fecha_creacion',
            new_name='fecha_publicacion',
        ),
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(default='Descripción pendiente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
